### ISSUE TITLE
开发环境运行调试报错

### ISSUE THREAD

**Issue by littletow** [timeromantic/hotDataList#56]
parse mysql config once. filePath: D:\go-workspace\TopList\Config\mysql.toml
2019/09/26 15:01:52 err
2019/09/26 15:01:52 http: panic serving [::1]:62895: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc00005ec80)
	C:/Go/src/net/http/server.go:1769 +0xd0
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.errRecover(0xc00007bc20)
	C:/Go/src/text/template/exec.go:160 +0x1d4
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.(*Template).execute(0x0, 0x8c9060, 0xc000126000, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/text/template/exec.go:214 +0x1a9
text/template.(*Template).Execute(...)
	C:/Go/src/text/template/exec.go:200
main.main.func1(0x8d0020, 0xc000126000, 0xc000112000)
	D:/go-workspace/TopList/App/Server.go:72 +0xd0
net/http.HandlerFunc.ServeHTTP(0x85d398, 0x8d0020, 0xc000126000, 0xc000112000)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb77500, 0x8d0020, 0xc000126000, 0xc000112000)
	C:/Go/src/net/http/server.go:2375 +0x1dd
net/http.serverHandler.ServeHTTP(0xc00005c9c0, 0x8d0020, 0xc000126000, 0xc000112000)
	C:/Go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc00005ec80, 0x8d08e0, 0xc000104040)
	C:/Go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/09/26 15:01:52 err
2019/09/26 15:01:52 http: panic serving [::1]:62896: runtime error: invalid memory address or nil pointer dereference
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc000164000)
	C:/Go/src/net/http/server.go:1769 +0xd0
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.errRecover(0xc0000f7c20)
	C:/Go/src/text/template/exec.go:160 +0x1d4
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.(*Template).execute(0x0, 0x8c9060, 0xc000176000, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/text/template/exec.go:214 +0x1a9
text/template.(*Template).Execute(...)
	C:/Go/src/text/template/exec.go:200
main.main.func1(0x8d0020, 0xc000176000, 0xc00016a000)
	D:/go-workspace/TopList/App/Server.go:72 +0xd0
net/http.HandlerFunc.ServeHTTP(0x85d398, 0x8d0020, 0xc000176000, 0xc00016a000)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb77500, 0x8d0020, 0xc000176000, 0xc00016a000)
	C:/Go/src/net/http/server.go:2375 +0x1dd
net/http.serverHandler.ServeHTTP(0xc00005c9c0, 0x8d0020, 0xc000176000, 0xc00016a000)
	C:/Go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc000164000, 0x8d08e0, 0xc0000180c0)
	C:/Go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/09/26 15:01:57 err
2019/09/26 15:01:57 http: panic serving [::1]:62897: runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc00005ed20)
	C:/Go/src/net/http/server.go:1769 +0xd0
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.errRecover(0xc0000f9c20)
	C:/Go/src/text/template/exec.go:160 +0x1d4
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.(*Template).execute(0x0, 0x8c9060, 0xc0001760e0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/text/template/exec.go:214 +0x1a9
text/template.(*Template).Execute(...)
	C:/Go/src/text/template/exec.go:200
main.main.func1(0x8d0020, 0xc0001760e0, 0xc00016a100)
	D:/go-workspace/TopList/App/Server.go:72 +0xd0
net/http.HandlerFunc.ServeHTTP(0x85d398, 0x8d0020, 0xc0001760e0, 0xc00016a100)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb77500, 0x8d0020, 0xc0001760e0, 0xc00016a100)
	C:/Go/src/net/http/server.go:2375 +0x1dd
net/http.serverHandler.ServeHTTP(0xc00005c9c0, 0x8d0020, 0xc0001760e0, 0xc00016a100)
	C:/Go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc00005ed20, 0x8d08e0, 0xc000018280)
	C:/Go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/09/26 15:02:27 err
2019/09/26 15:02:27 http: panic serving [::1]:62902: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc00016e0a0)
	C:/Go/src/net/http/server.go:1769 +0xd0
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.errRecover(0xc0000f9c20)
	C:/Go/src/text/template/exec.go:160 +0x1d4
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.(*Template).execute(0x0, 0x8c9060, 0xc0001b0000, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/text/template/exec.go:214 +0x1a9
text/template.(*Template).Execute(...)
	C:/Go/src/text/template/exec.go:200
main.main.func1(0x8d0020, 0xc0001b0000, 0xc0001aa000)
	D:/go-workspace/TopList/App/Server.go:72 +0xd0
net/http.HandlerFunc.ServeHTTP(0x85d398, 0x8d0020, 0xc0001b0000, 0xc0001aa000)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb77500, 0x8d0020, 0xc0001b0000, 0xc0001aa000)
	C:/Go/src/net/http/server.go:2375 +0x1dd
net/http.serverHandler.ServeHTTP(0xc00005c9c0, 0x8d0020, 0xc0001b0000, 0xc0001aa000)
	C:/Go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc00016e0a0, 0x8d08e0, 0xc000060580)
	C:/Go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/09/26 15:03:27 err
2019/09/26 15:03:27 http: panic serving [::1]:62909: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc00016e140)
	C:/Go/src/net/http/server.go:1769 +0xd0
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.errRecover(0xc0000f7c20)
	C:/Go/src/text/template/exec.go:160 +0x1d4
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.(*Template).execute(0x0, 0x8c9060, 0xc0001b00e0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/text/template/exec.go:214 +0x1a9
text/template.(*Template).Execute(...)
	C:/Go/src/text/template/exec.go:200
main.main.func1(0x8d0020, 0xc0001b00e0, 0xc0001aa100)
	D:/go-workspace/TopList/App/Server.go:72 +0xd0
net/http.HandlerFunc.ServeHTTP(0x85d398, 0x8d0020, 0xc0001b00e0, 0xc0001aa100)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb77500, 0x8d0020, 0xc0001b00e0, 0xc0001aa100)
	C:/Go/src/net/http/server.go:2375 +0x1dd
net/http.serverHandler.ServeHTTP(0xc00005c9c0, 0x8d0020, 0xc0001b00e0, 0xc0001aa100)
	C:/Go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc00016e140, 0x8d08e0, 0xc0000606c0)
	C:/Go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/09/26 15:06:33 err
2019/09/26 15:06:33 http: panic serving [::1]:62943: runtime error: invalid memory address or nil pointer dereference
goroutine 25 [running]:
net/http.(*conn).serve.func1(0xc00005ef00)
	C:/Go/src/net/http/server.go:1769 +0xd0
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.errRecover(0xc00007bc20)
	C:/Go/src/text/template/exec.go:160 +0x1d4
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.(*Template).execute(0x0, 0x8c9060, 0xc0001762a0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/text/template/exec.go:214 +0x1a9
text/template.(*Template).Execute(...)
	C:/Go/src/text/template/exec.go:200
main.main.func1(0x8d0020, 0xc0001762a0, 0xc00016a400)
	D:/go-workspace/TopList/App/Server.go:72 +0xd0
net/http.HandlerFunc.ServeHTTP(0x85d398, 0x8d0020, 0xc0001762a0, 0xc00016a400)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb77500, 0x8d0020, 0xc0001762a0, 0xc00016a400)
	C:/Go/src/net/http/server.go:2375 +0x1dd
net/http.serverHandler.ServeHTTP(0xc00005c9c0, 0x8d0020, 0xc0001762a0, 0xc00016a400)
	C:/Go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc00005ef00, 0x8d08e0, 0xc000018380)
	C:/Go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/09/26 15:06:33 err
2019/09/26 15:06:33 http: panic serving [::1]:62945: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
net/http.(*conn).serve.func1(0xc00016e320)
	C:/Go/src/net/http/server.go:1769 +0xd0
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.errRecover(0xc0001b5c20)
	C:/Go/src/text/template/exec.go:160 +0x1d4
panic(0x7d7f00, 0xb6ac20)
	C:/Go/src/runtime/panic.go:522 +0x1c3
text/template.(*Template).execute(0x0, 0x8c9060, 0xc0001260e0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/text/template/exec.go:214 +0x1a9
text/template.(*Template).Execute(...)
	C:/Go/src/text/template/exec.go:200
main.main.func1(0x8d0020, 0xc0001260e0, 0xc000112200)
	D:/go-workspace/TopList/App/Server.go:72 +0xd0
net/http.HandlerFunc.ServeHTTP(0x85d398, 0x8d0020, 0xc0001260e0, 0xc000112200)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb77500, 0x8d0020, 0xc0001260e0, 0xc000112200)
	C:/Go/src/net/http/server.go:2375 +0x1dd
net/http.serverHandler.ServeHTTP(0xc00005c9c0, 0x8d0020, 0xc0001260e0, 0xc000112200)
	C:/Go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc00016e320, 0x8d08e0, 0xc000104340)
	C:/Go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb

当在浏览器输入localhost:9090时报错。localhost:9090/GetType正常。

**Comment by littletow** [comment]
通过nginx部署可以了。
